const char *page =
"<html>"
"<head>"
    "<meta charset=\"utf-8\">"
	"<title>Programming terminal</title>"
	"<script>"
		"function load() {"
			"document.querySelector('#in').focus();"
		"}"
		"function send() {"
			"var e = document.querySelector('#in');"
			"var xhr = new XMLHttpRequest();"
			"xhr.open('POST', '/text');"
			"xhr.send(e.value);"
		"}"
	"</script>"
	"<style>"
        "h1 {"
            "color: white;"
            "background: #000080;"
            "padding: 10px;"
            "border-radius: 5px;"
            "margin-bottom: 5px;"
        "}"
        "body {"
            "font-family: monospace;"
            "padding: 0;"
        "}"
        "input, textarea, button {"
            "border-style: solid;"
            "border-radius: 3px;"
        "}"
        "td {"
            "width: auto;"
        "}"
        "td.min {"
            "width: 1%;"
        "}"
        "#in {"
            "width: 100%;"
            "height: 300px;"
        "}"
        "#send {"
            "margin-bottom: 10px;"
        "}"
        "table {"
            "width: 100%;"
        "}"		  
    "</style>"
"</head>"
"<body onload='load()'>"
	"<h1>Программный терминал</h1>"
	"<table>"
        "<tr>"
            "<td><p>В текстовое поле введите код программы. После нажатия кнопки 'Выполнить' программа выполнится на микроконтроллере.</p></td>"
        "</tr>"
		"<tr>"
			"<td colspan=2>"
				"<textarea id='in' type='text' tabindex=1 autocomplete='off'>"
                "</textarea>"
			"</td>"
		"</tr>"
        "<tr>"
			"<td class='min'><button id='send' onclick='send()' tabindex=2>Выполнить</button></td>"
		"</tr>"
	"</table>"
"</body>"

"</html>";